import type { Locale } from "@/lib/i18n"

export const telegramCopy = {
  uz: {
    appName: "Factory OS",
    orders: "Buyurtmalar",
    waiting: "Kutilmoqda",
    notifications: "Xabarlar",
    unread: "O‘qilmagan",
    allOrders: "Mening buyurtmalarim",
    waitingOrders: "Amalimni kutmoqda",
    totalOrders: "Jami buyurtmalar",
    actionRequired: "Amal kerak",
    urgentOrders: "Shoshilinch",
    ordersSection: "Buyurtmalar ro‘yxati",
    orderInformation: "Buyurtma haqida",
    orderProgress: "Jarayon holati",
    ordersSubtitle: "Ish jarayonidagi barcha tegishli buyurtmalar",
    waitingSubtitle: "Sizning harakatingiz talab qilinadigan buyurtmalar",
    noOrders: "Buyurtmalar topilmadi",
    noOrdersBody: "Sizga tegishli buyurtmalar shu yerda ko‘rinadi.",
    noWaiting: "Hozircha vazifa yo‘q",
    noWaitingBody: "Amalingizni kutayotgan buyurtma paydo bo‘lsa, bot sizga xabar beradi.",
    noNotifications: "Yangi xabarlar yo‘q",
    noNotificationsBody: "Buyurtma holatidagi o‘zgarishlar shu yerda ko‘rinadi.",
    items: "pozitsiya",
    applicant: "Arizachi",
    department: "Bo‘lim",
    warehouse: "Ombor",
    purpose: "Maqsad",
    expectedDate: "Kutilayotgan sana",
    createdAt: "Yaratilgan",
    urgency: "Shoshilinchlik",
    type: "Turi",
    material: "Material",
    service: "Xizmat",
    comment: "Izoh",
    positions: "Pozitsiyalar",
    quantity: "Miqdor",
    openOrder: "Buyurtmani ochish",
    backToOrders: "Buyurtmalarga qaytish",
    orderNotFound: "Buyurtma topilmadi",
    status: {
      draft: "Qoralama",
      in_review: "Ko‘rib chiqilmoqda",
      revision_requested: "Qayta ishlashda",
      approved: "Tasdiqlangan",
      rejected: "Rad etilgan",
      cancelled: "Bekor qilingan",
    },
    urgencyLabels: { normal: "Oddiy", high: "Yuqori", urgent: "Shoshilinch", critical: "Juda shoshilinch" },
  },
  ru: {
    appName: "Factory OS",
    orders: "Заявки",
    waiting: "Ожидают",
    notifications: "Сообщения",
    unread: "Непрочитанные",
    allOrders: "Мои заявки",
    waitingOrders: "Ожидают моего действия",
    totalOrders: "Всего заявок",
    actionRequired: "Нужно действие",
    urgentOrders: "Срочные",
    ordersSection: "Список заявок",
    orderInformation: "О заявке",
    orderProgress: "Ход заявки",
    ordersSubtitle: "Все связанные с вами заявки в рабочем процессе",
    waitingSubtitle: "Заявки, по которым требуется ваше действие",
    noOrders: "Заявки не найдены",
    noOrdersBody: "Связанные с вами заявки появятся здесь.",
    noWaiting: "Сейчас задач нет",
    noWaitingBody: "Бот сообщит, когда заявка будет ожидать вашего действия.",
    noNotifications: "Новых сообщений нет",
    noNotificationsBody: "Изменения статуса заявок появятся здесь.",
    items: "позиций",
    applicant: "Заявитель",
    department: "Отдел",
    warehouse: "Склад",
    purpose: "Назначение",
    expectedDate: "Ожидаемая дата",
    createdAt: "Создана",
    urgency: "Срочность",
    type: "Тип",
    material: "Материал",
    service: "Услуга",
    comment: "Комментарий",
    positions: "Позиции",
    quantity: "Количество",
    openOrder: "Открыть заявку",
    backToOrders: "Вернуться к заявкам",
    orderNotFound: "Заявка не найдена",
    status: {
      draft: "Черновик",
      in_review: "На рассмотрении",
      revision_requested: "На доработке",
      approved: "Одобрена",
      rejected: "Отклонена",
      cancelled: "Отменена",
    },
    urgencyLabels: { normal: "Обычная", high: "Высокая", urgent: "Срочная", critical: "Критическая" },
  },
  tr: {
    appName: "Factory OS",
    orders: "Siparişler",
    waiting: "Bekleyenler",
    notifications: "Bildirimler",
    unread: "Okunmamış",
    allOrders: "Siparişlerim",
    waitingOrders: "İşlemimi bekleyenler",
    totalOrders: "Toplam sipariş",
    actionRequired: "İşlem gerekli",
    urgentOrders: "Acil",
    ordersSection: "Sipariş listesi",
    orderInformation: "Sipariş bilgileri",
    orderProgress: "Sipariş süreci",
    ordersSubtitle: "İş akışında sizinle ilgili tüm siparişler",
    waitingSubtitle: "İşleminizi gerektiren siparişler",
    noOrders: "Sipariş bulunamadı",
    noOrdersBody: "Sizinle ilgili siparişler burada görünür.",
    noWaiting: "Şimdilik görev yok",
    noWaitingBody: "Bir sipariş işleminizi beklediğinde bot size bildirir.",
    noNotifications: "Yeni bildirim yok",
    noNotificationsBody: "Sipariş durumu değişiklikleri burada görünür.",
    items: "kalem",
    applicant: "Talep sahibi",
    department: "Departman",
    warehouse: "Depo",
    purpose: "Amaç",
    expectedDate: "Beklenen tarih",
    createdAt: "Oluşturuldu",
    urgency: "Aciliyet",
    type: "Tür",
    material: "Malzeme",
    service: "Hizmet",
    comment: "Açıklama",
    positions: "Kalemler",
    quantity: "Miktar",
    openOrder: "Siparişi aç",
    backToOrders: "Siparişlere dön",
    orderNotFound: "Sipariş bulunamadı",
    status: {
      draft: "Taslak",
      in_review: "İnceleniyor",
      revision_requested: "Düzeltmede",
      approved: "Onaylandı",
      rejected: "Reddedildi",
      cancelled: "İptal edildi",
    },
    urgencyLabels: { normal: "Normal", high: "Yüksek", urgent: "Acil", critical: "Kritik" },
  },
} satisfies Record<Locale, Record<string, unknown>>

export type TelegramCopy = (typeof telegramCopy)[Locale]
