import type { Locale } from "@/lib/i18n"

export const telegramCopy = {
  uz: {
    appName: "Factory OS",
    orders: "Buyurtmalar",
    waiting: "Kutilmoqda",
    notifications: "Xabarlar",
    settings: "Sozlamalar",
    unread: "O‘qilmagan",
    allOrders: "Mening buyurtmalarim",
    waitingOrders: "Amalimni kutmoqda",
    totalOrders: "Jami buyurtmalar",
    actionRequired: "Amal kerak",
    urgentOrders: "Shoshilinch",
    goodDay: "Xayrli kun,",
    employee: "Xodim",
    workOverview: "Ish holati",
    ordersSection: "Buyurtmalar ro‘yxati",
    language: "Til",
    switchTheme: "Rang rejimini almashtirish",
    filters: "Filtrlar",
    applyFilters: "Qo‘llash",
    clearFilters: "Tozalash",
    allOptions: "Barchasi",
    statusLabel: "Holati",
    searchOrders: "Buyurtmalarni qidirish",
    searchPlaceholder: "Raqam, arizachi yoki maqsad...",
    orderInformation: "Buyurtma haqida",
    orderProgress: "Jarayon holati",
    ordersSubtitle: "Ish jarayonidagi barcha tegishli buyurtmalar",
    waitingSubtitle: "Sizning harakatingiz talab qilinadigan buyurtmalar",
    noOrders: "Buyurtmalar topilmadi",
    noOrdersBody: "Sizga tegishli buyurtmalar shu yerda ko‘rinadi.",
    noWaiting: "Hozircha vazifa yo‘q",
    noWaitingBody: "Amalingizni kutayotgan buyurtma paydo bo‘lsa, bot sizga xabar beradi.",
    noNotifications: "Yangi xabarlar yo‘q",
    noNotificationsBody: "Buyurtma holatidagi o‘zgarishlar shu yerda ko‘rinadi.",
    items: "pozitsiya",
    applicant: "Arizachi",
    department: "Bo‘lim",
    warehouse: "Ombor",
    purpose: "Maqsad",
    expectedDate: "Kutilayotgan sana",
    createdAt: "Yaratilgan",
    urgency: "Shoshilinchlik",
    type: "Turi",
    material: "Material",
    service: "Xizmat",
    comment: "Izoh",
    positions: "Pozitsiyalar",
    quantity: "Miqdor",
    openOrder: "Buyurtmani ochish",
    backToOrders: "Buyurtmalarga qaytish",
    orderNotFound: "Buyurtma topilmadi",
    settingsSubtitle: "Shaxsiy hisob va Telegram ulanishi",
    personalDetails: "Shaxsiy ma’lumotlar",
    personalDetailsHelp: "Ism, login va Telegram bilan bog‘langan ish raqamingizni yangilang.",
    fullName: "To‘liq ism",
    username: "Login",
    telegramPhone: "Telegram telefon raqami",
    telegramPhoneHelp: "Bot sizni aynan shu raqam orqali taniydi. Mamlakat kodi bilan kiriting.",
    saveChanges: "O‘zgarishlarni saqlash",
    saving: "Saqlanmoqda…",
    profileSaved: "Profil yangilandi.",
    profileSaveFailed: "Profilni yangilab bo‘lmadi.",
    usernameAlreadyExists: "Bu login allaqachon ishlatilmoqda.",
    phoneAlreadyExists: "Bu telefon raqami boshqa foydalanuvchiga biriktirilgan.",
    invalidPhone: "Telefon raqamini mamlakat kodi bilan to‘g‘ri kiriting.",
    profilePhoto: "Profil rasmi",
    choosePhoto: "Rasmni almashtirish",
    photoHelp: "JPG, PNG, WebP yoki GIF. Maksimal hajm 5 MB.",
    uploadingPhoto: "Yuklanmoqda…",
    photoUpdated: "Profil rasmi yangilandi.",
    photoUploadFailed: "Rasmni yuklab bo‘lmadi.",
    telegramConnection: "Telegram ulanishi",
    telegramConnected: "Telegram ulangan",
    telegramNotConnected: "Telegram ulanmagan",
    telegramConnectionHelp: "Ulanish bot xabarlari va Mini App’ga xavfsiz kirishni ta’minlaydi.",
    relinkTelegram: "Yangi hisobni ulash uchun botga qayting, /start yuboring va shu raqamni ulashing.",
    disconnectTelegram: "Telegramni uzish",
    disconnectTelegramConfirm: "Telegram ulanishini uzasizmi? Qayta ulash uchun botga /start yuborish kerak bo‘ladi.",
    telegramDisconnected: "Telegram uzildi. Yangi hisobni ulash uchun botga /start yuboring.",
    telegramDisconnectFailed: "Telegram ulanishini uzib bo‘lmadi.",
    security: "Xavfsizlik",
    securityHelp: "Hisobingiz uchun yangi parol o‘rnating.",
    currentPassword: "Joriy parol",
    newPassword: "Yangi parol",
    confirmPassword: "Yangi parolni tasdiqlang",
    changePassword: "Parolni almashtirish",
    changingPassword: "Almashtirilmoqda…",
    passwordTooShort: "Yangi parol kamida 8 ta belgidan iborat bo‘lishi kerak.",
    passwordMismatch: "Yangi parollar bir xil emas.",
    currentPasswordIncorrect: "Joriy parol noto‘g‘ri.",
    passwordChanged: "Parol almashtirildi.",
    passwordChangeFailed: "Parolni almashtirib bo‘lmadi.",
    status: {
      draft: "Qoralama",
      in_review: "Ko‘rib chiqilmoqda",
      revision_requested: "Qayta ishlashda",
      approved: "Tasdiqlangan",
      rejected: "Rad etilgan",
      cancelled: "Bekor qilingan",
    },
    urgencyLabels: { normal: "Oddiy", high: "Yuqori", urgent: "Shoshilinch", critical: "Juda shoshilinch" },
  },
  ru: {
    appName: "Factory OS",
    orders: "Заявки",
    waiting: "Ожидают",
    notifications: "Сообщения",
    settings: "Настройки",
    unread: "Непрочитанные",
    allOrders: "Мои заявки",
    waitingOrders: "Ожидают моего действия",
    totalOrders: "Всего заявок",
    actionRequired: "Нужно действие",
    urgentOrders: "Срочные",
    goodDay: "Добрый день,",
    employee: "Сотрудник",
    workOverview: "Рабочая сводка",
    ordersSection: "Список заявок",
    language: "Язык",
    switchTheme: "Сменить тему",
    filters: "Фильтры",
    applyFilters: "Применить",
    clearFilters: "Сбросить",
    allOptions: "Все",
    statusLabel: "Статус",
    searchOrders: "Поиск заявок",
    searchPlaceholder: "Номер, заявитель или назначение...",
    orderInformation: "О заявке",
    orderProgress: "Ход заявки",
    ordersSubtitle: "Все связанные с вами заявки в рабочем процессе",
    waitingSubtitle: "Заявки, по которым требуется ваше действие",
    noOrders: "Заявки не найдены",
    noOrdersBody: "Связанные с вами заявки появятся здесь.",
    noWaiting: "Сейчас задач нет",
    noWaitingBody: "Бот сообщит, когда заявка будет ожидать вашего действия.",
    noNotifications: "Новых сообщений нет",
    noNotificationsBody: "Изменения статуса заявок появятся здесь.",
    items: "позиций",
    applicant: "Заявитель",
    department: "Отдел",
    warehouse: "Склад",
    purpose: "Назначение",
    expectedDate: "Ожидаемая дата",
    createdAt: "Создана",
    urgency: "Срочность",
    type: "Тип",
    material: "Материал",
    service: "Услуга",
    comment: "Комментарий",
    positions: "Позиции",
    quantity: "Количество",
    openOrder: "Открыть заявку",
    backToOrders: "Вернуться к заявкам",
    orderNotFound: "Заявка не найдена",
    settingsSubtitle: "Личный аккаунт и подключение Telegram",
    personalDetails: "Личные данные",
    personalDetailsHelp: "Обновите имя, логин и рабочий номер, связанный с Telegram.",
    fullName: "Полное имя",
    username: "Логин",
    telegramPhone: "Номер телефона Telegram",
    telegramPhoneHelp: "Бот находит вас по этому номеру. Укажите его с кодом страны.",
    saveChanges: "Сохранить изменения",
    saving: "Сохраняем…",
    profileSaved: "Профиль обновлён.",
    profileSaveFailed: "Не удалось обновить профиль.",
    usernameAlreadyExists: "Этот логин уже используется.",
    phoneAlreadyExists: "Этот номер привязан к другому пользователю.",
    invalidPhone: "Введите корректный номер с кодом страны.",
    profilePhoto: "Фото профиля",
    choosePhoto: "Изменить фото",
    photoHelp: "JPG, PNG, WebP или GIF. Не более 5 МБ.",
    uploadingPhoto: "Загружаем…",
    photoUpdated: "Фото профиля обновлено.",
    photoUploadFailed: "Не удалось загрузить фото.",
    telegramConnection: "Подключение Telegram",
    telegramConnected: "Telegram подключён",
    telegramNotConnected: "Telegram не подключён",
    telegramConnectionHelp: "Подключение обеспечивает уведомления бота и безопасный вход в Mini App.",
    relinkTelegram: "Чтобы подключить новый аккаунт, вернитесь в бот, отправьте /start и поделитесь этим номером.",
    disconnectTelegram: "Отключить Telegram",
    disconnectTelegramConfirm: "Отключить Telegram? Для повторного подключения нужно будет отправить боту /start.",
    telegramDisconnected: "Telegram отключён. Отправьте боту /start, чтобы подключить новый аккаунт.",
    telegramDisconnectFailed: "Не удалось отключить Telegram.",
    security: "Безопасность",
    securityHelp: "Установите новый пароль для своего аккаунта.",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Повторите новый пароль",
    changePassword: "Изменить пароль",
    changingPassword: "Изменяем…",
    passwordTooShort: "Новый пароль должен содержать не менее 8 символов.",
    passwordMismatch: "Новые пароли не совпадают.",
    currentPasswordIncorrect: "Текущий пароль указан неверно.",
    passwordChanged: "Пароль изменён.",
    passwordChangeFailed: "Не удалось изменить пароль.",
    status: {
      draft: "Черновик",
      in_review: "На рассмотрении",
      revision_requested: "На доработке",
      approved: "Одобрена",
      rejected: "Отклонена",
      cancelled: "Отменена",
    },
    urgencyLabels: { normal: "Обычная", high: "Высокая", urgent: "Срочная", critical: "Критическая" },
  },
  tr: {
    appName: "Factory OS",
    orders: "Siparişler",
    waiting: "Bekleyenler",
    notifications: "Bildirimler",
    settings: "Ayarlar",
    unread: "Okunmamış",
    allOrders: "Siparişlerim",
    waitingOrders: "İşlemimi bekleyenler",
    totalOrders: "Toplam sipariş",
    actionRequired: "İşlem gerekli",
    urgentOrders: "Acil",
    goodDay: "İyi günler,",
    employee: "Çalışan",
    workOverview: "İş özeti",
    ordersSection: "Sipariş listesi",
    language: "Dil",
    switchTheme: "Temayı değiştir",
    filters: "Filtreler",
    applyFilters: "Uygula",
    clearFilters: "Temizle",
    allOptions: "Tümü",
    statusLabel: "Durum",
    searchOrders: "Siparişlerde ara",
    searchPlaceholder: "Numara, talep sahibi veya amaç...",
    orderInformation: "Sipariş bilgileri",
    orderProgress: "Sipariş süreci",
    ordersSubtitle: "İş akışında sizinle ilgili tüm siparişler",
    waitingSubtitle: "İşleminizi gerektiren siparişler",
    noOrders: "Sipariş bulunamadı",
    noOrdersBody: "Sizinle ilgili siparişler burada görünür.",
    noWaiting: "Şimdilik görev yok",
    noWaitingBody: "Bir sipariş işleminizi beklediğinde bot size bildirir.",
    noNotifications: "Yeni bildirim yok",
    noNotificationsBody: "Sipariş durumu değişiklikleri burada görünür.",
    items: "kalem",
    applicant: "Talep sahibi",
    department: "Departman",
    warehouse: "Depo",
    purpose: "Amaç",
    expectedDate: "Beklenen tarih",
    createdAt: "Oluşturuldu",
    urgency: "Aciliyet",
    type: "Tür",
    material: "Malzeme",
    service: "Hizmet",
    comment: "Açıklama",
    positions: "Kalemler",
    quantity: "Miktar",
    openOrder: "Siparişi aç",
    backToOrders: "Siparişlere dön",
    orderNotFound: "Sipariş bulunamadı",
    settingsSubtitle: "Kişisel hesap ve Telegram bağlantısı",
    personalDetails: "Kişisel bilgiler",
    personalDetailsHelp: "Adınızı, kullanıcı adınızı ve Telegram’a bağlı iş numaranızı güncelleyin.",
    fullName: "Ad soyad",
    username: "Kullanıcı adı",
    telegramPhone: "Telegram telefon numarası",
    telegramPhoneHelp: "Bot sizi bu numarayla tanır. Ülke koduyla girin.",
    saveChanges: "Değişiklikleri kaydet",
    saving: "Kaydediliyor…",
    profileSaved: "Profil güncellendi.",
    profileSaveFailed: "Profil güncellenemedi.",
    usernameAlreadyExists: "Bu kullanıcı adı zaten kullanılıyor.",
    phoneAlreadyExists: "Bu telefon numarası başka bir kullanıcıya bağlı.",
    invalidPhone: "Ülke koduyla geçerli bir telefon numarası girin.",
    profilePhoto: "Profil fotoğrafı",
    choosePhoto: "Fotoğrafı değiştir",
    photoHelp: "JPG, PNG, WebP veya GIF. En fazla 5 MB.",
    uploadingPhoto: "Yükleniyor…",
    photoUpdated: "Profil fotoğrafı güncellendi.",
    photoUploadFailed: "Fotoğraf yüklenemedi.",
    telegramConnection: "Telegram bağlantısı",
    telegramConnected: "Telegram bağlı",
    telegramNotConnected: "Telegram bağlı değil",
    telegramConnectionHelp: "Bağlantı, bot bildirimlerini ve Mini App’e güvenli girişi sağlar.",
    relinkTelegram: "Yeni bir hesap bağlamak için bota dönün, /start gönderin ve bu numarayı paylaşın.",
    disconnectTelegram: "Telegram bağlantısını kes",
    disconnectTelegramConfirm: "Telegram bağlantısı kesilsin mi? Yeniden bağlamak için bota /start göndermeniz gerekir.",
    telegramDisconnected: "Telegram bağlantısı kesildi. Yeni hesabı bağlamak için bota /start gönderin.",
    telegramDisconnectFailed: "Telegram bağlantısı kesilemedi.",
    security: "Güvenlik",
    securityHelp: "Hesabınız için yeni bir şifre belirleyin.",
    currentPassword: "Mevcut şifre",
    newPassword: "Yeni şifre",
    confirmPassword: "Yeni şifreyi doğrulayın",
    changePassword: "Şifreyi değiştir",
    changingPassword: "Değiştiriliyor…",
    passwordTooShort: "Yeni şifre en az 8 karakter olmalıdır.",
    passwordMismatch: "Yeni şifreler eşleşmiyor.",
    currentPasswordIncorrect: "Mevcut şifre yanlış.",
    passwordChanged: "Şifre değiştirildi.",
    passwordChangeFailed: "Şifre değiştirilemedi.",
    status: {
      draft: "Taslak",
      in_review: "İnceleniyor",
      revision_requested: "Düzeltmede",
      approved: "Onaylandı",
      rejected: "Reddedildi",
      cancelled: "İptal edildi",
    },
    urgencyLabels: { normal: "Normal", high: "Yüksek", urgent: "Acil", critical: "Kritik" },
  },
} satisfies Record<Locale, Record<string, unknown>>

export type TelegramCopy = (typeof telegramCopy)[Locale]
