export const orderPaymentCopy = {
  uz: {
    selectionHint: "Rasmiylashtirish uchun mahsulotlarni tanlang. Bitta pozitsiya bir nechta yetkazib beruvchiga bo‘lingan bo‘lsa, uning barcha qismlari birga tanlanadi.", selectSupplier: "Yetkazib beruvchining barcha mahsulotlarini tanlash", selected: "Tanlangan pozitsiyalar", originalMethods: "Taklifdagi shakllarni saqlash",
    shortTitle: "Rasmiylashtirish", selectPosition: "Pozitsiyani tanlash", inn: "Yetkazib beruvchi INN’i", innRequired: "INN kiriting", innLocked: "Saqlangan INN o‘zgartirilmaydi.", innOnce: "Bir marta kiritiladi va yetkazib beruvchida saqlanadi.",
    title: "Buyurtmani rasmiylashtirish", description: "Har bir yetkazib beruvchi ma’lumotlarini bir marta kiriting. To‘lov shartlari guruhdagi tanlangan mahsulotlarga qo‘llanadi; avans summa bo‘yicha taqsimlanadi. Tanlovni o‘zgartirish uchun orqaga qayting.",
    product: "Mahsulot / yetkazib beruvchi", method: "To‘lov shakli", bank: "Bank o‘tkazmasi", cash: "Naqd", percent: "Avans, %", advance: "Avans, UZS", due: "Qolgan to‘lov muddati", contract: "Shartnoma raqami", file: "Shartnoma fayli", remaining: "Qoldiq", total: "Jami", cancel: "Bekor qilish", save: "Saqlash va yuborish", saving: "Saqlanmoqda…", loading: "Tasdiqlangan takliflar yuklanmoqda…", retry: "Qayta yuklash", saved: "To‘lov shartlari", optional: "Ixtiyoriy", hint: "Fayl: 5 MB gacha, jami 20 MB dan kam. Bu forma to‘lovni amalga oshirmaydi, faqat shartlarini saqlaydi.",
    failed: "Saqlanmadi. Qayta urinib ko‘ring.", invalid: "To‘lov ma’lumotlarini tekshiring. Avans jami summadan oshmasin; qoldiq uchun muddatni kiriting.", changed: "Buyurtma yoki takliflar o‘zgargan. Buyurtmani qayta oching.", large: "Har bir fayl 5 MB gacha, jami 20 MB dan kam bo‘lishi kerak.", empty: "To‘liq tasdiqlangan takliflar topilmadi.",
  },
  ru: {
    selectionHint: "Выберите товары для оформления. Если позиция разделена между поставщиками, все её части выбираются вместе.", selectSupplier: "Выбрать все товары поставщика", selected: "Выбрано позиций", originalMethods: "Сохранить формы из предложений",
    shortTitle: "Оформить", selectPosition: "Выбрать позицию", inn: "ИНН поставщика", innRequired: "Введите ИНН", innLocked: "Сохранённый ИНН нельзя изменить.", innOnce: "Вводится один раз и сохраняется у поставщика.",
    title: "Оформить заказ", description: "Введите данные каждого поставщика один раз. Условия действуют для выбранных товаров группы; аванс распределяется по стоимости. Чтобы изменить выбор, вернитесь назад.",
    product: "Товар / поставщик", method: "Форма оплаты", bank: "Банковский перевод", cash: "Наличные", percent: "Аванс, %", advance: "Аванс, UZS", due: "Срок остатка оплаты", contract: "Номер договора", file: "Файл договора", remaining: "Остаток", total: "Итого", cancel: "Отмена", save: "Сохранить и отправить", saving: "Сохранение…", loading: "Загрузка утверждённых предложений…", retry: "Загрузить заново", saved: "Условия оплаты", optional: "Необязательно", hint: "До 5 МБ на файл, суммарно менее 20 МБ. Форма сохраняет условия, а не выполняет платёж.",
    failed: "Не удалось сохранить. Попробуйте ещё раз.", invalid: "Проверьте условия: аванс не больше суммы; для остатка укажите срок оплаты.", changed: "Заказ или предложения изменились. Откройте заказ заново.", large: "До 5 МБ на файл, суммарно менее 20 МБ.", empty: "Полные утверждённые предложения не найдены.",
  },
  tr: {
    selectionHint: "Sipariş verilecek ürünleri seçin. Bir kalem birden fazla tedarikçiye bölünmüşse tüm parçaları birlikte seçilir.", selectSupplier: "Tedarikçinin tüm ürünlerini seç", selected: "Seçilen kalemler", originalMethods: "Teklifteki ödeme şekillerini koru",
    shortTitle: "Sipariş oluştur", selectPosition: "Kalem seç", inn: "Tedarikçi vergi numarası", innRequired: "Vergi numarasını girin", innLocked: "Kayıtlı vergi numarası değiştirilemez.", innOnce: "Bir kez girilir ve tedarikçiye kaydedilir.",
    title: "Siparişi oluştur", description: "Her tedarikçinin bilgilerini bir kez girin. Koşullar gruptaki seçilen ürünlere uygulanır; avans tutara göre dağıtılır. Seçimi değiştirmek için geri dönün.",
    product: "Ürün / tedarikçi", method: "Ödeme şekli", bank: "Banka havalesi", cash: "Nakit", percent: "Avans, %", advance: "Avans, UZS", due: "Kalan ödeme tarihi", contract: "Sözleşme numarası", file: "Sözleşme dosyası", remaining: "Kalan", total: "Toplam", cancel: "İptal", save: "Kaydet ve gönder", saving: "Kaydediliyor…", loading: "Onaylı teklifler yükleniyor…", retry: "Yeniden yükle", saved: "Ödeme koşulları", optional: "İsteğe bağlı", hint: "Dosya başına 5 MB, toplam 20 MB altında. Bu form ödeme yapmaz, yalnızca koşulları kaydeder.",
    failed: "Kaydedilemedi. Tekrar deneyin.", invalid: "Avans tutarını ve kalan ödeme tarihini kontrol edin.", changed: "Sipariş veya teklifler değişti. Siparişi yeniden açın.", large: "Dosya başına 5 MB, toplam 20 MB altında olmalıdır.", empty: "Eksiksiz onaylı teklifler bulunamadı.",
  },
} as const
